### ISSUE TITLE
e2e cypress not compatible with mro for e2e testing

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-quickstarters#165]
**Describe the bug**
Newly provisioned e2e cypress quickstarter - if added to the mro with type `ods-test` fails because mro expects three xmlUnit files

java.lang.RuntimeException: Error: unable to unstash JUnit XML reports for repo 'e2e-cypress' from stash 'acceptance-test-reports-junit-xml-e2e-cypress-40'.
	at phaseTest.getTestResults(phaseTest.groovy:109)
	at phaseTest.getAcceptanceTestResults(phaseTest.groovy:87)
	at phaseTest.call(phaseTest.groovy:43)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:285)
	at org.ods.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:108)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:232)
	at ___cps.transform___(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at 

**Affected version (please complete the following information):**
 - OpenDevStack [2.x/master]

**Additional context**
https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/master/vars/phaseTest.groovy#L49-L57 

Junit reporter:
https://www.npmjs.com/package/cypress-junit-reporter

@metmajer  fyi

**Comment by metmajer** [comment]
Thanks @clemensutschig. Should we one of a kind with the e2e-spock-geb QS.

**Comment by michaelsauter** [comment]
@herrkoch Could you take a look at this?

**Comment by herrkoch** [comment]
Hi @michaelsauter, I am happy to help, I noted it down and will take a look the issue as soon as I find some time!

**Comment by herrkoch** [comment]
Hi @michaelsauter I attached a draft PR that should fix this issue. The quickstarter itself runs fine on Jenkins and now generates JUnit XML reports in the "expected" folder for the release manager. Unfortunately, provisioning the release manager in my playground failed so I could not test the full circle. Kudos to you and @akhilsoman for the help today!
