### ISSUE TITLE
E2E cypress scanning has issues

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#439]
**Describe the bug**
Build is green, but there is a problem during the SQ scan (against SonarQube server 8.4.1):
```
INFO: Sensor TypeScript analysis [javascript]
INFO: Found 1 tsconfig.json file(s): [/tmp/workspace/unitt-cd/unitt-cd-run-unitt-cypress-unitt-master/tsconfig.json]
INFO: 5 source files to be analyzed
INFO: Analyzing 5 files using tsconfig: /tmp/workspace/unitt-cd/unitt-cd-run-unitt-cypress-unitt-master/tsconfig.json
ERROR: You are using version of TypeScript 3.1.6 which is not supported; supported versions >=3.2.1
ERROR: If it's not possible to upgrade version of TypeScript used by the project, consider installing supported TypeScript version just for the time of analysis
ERROR: Failure during analysis, Node.js command to start eslint-bridge was: {NODE_PATH=/tmp/workspace/unitt-cd/unitt-cd-run-unitt-cypress-unitt-master/node_modules} node /tmp/workspace/unitt-cd/unitt-cd-run-unitt-cypress-unitt-master/.scannerwork/.sonartmp/eslint-bridge-bundle/package/bin/server 45178
java.lang.IllegalStateException: Unsupported TypeScript version
        at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.processParsingError(AbstractEslintSensor.java:149)
        at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.processResponse(AbstractEslintSensor.java:188)
        at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyze(TypeScriptSensor.java:154)
        at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyzeFilesWithTsConfig(TypeScriptSensor.java:141)
        at org.sonar.plugins.javascript.eslint.TypeScriptSensor.analyzeFiles(TypeScriptSensor.java:121)
        at org.sonar.plugins.javascript.eslint.AbstractEslintSensor.execute(AbstractEslintSensor.java:107)
        at org.sonar.plugins.javascript.eslint.TypeScriptSensor.execute(TypeScriptSensor.java:53)
        at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
        at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
        at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:388)
        at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:384)
        at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:353)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
        at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
        at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
        at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
        at com.sun.proxy.$Proxy0.execute(Unknown Source)
        at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
        at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)

INFO: Sensor TypeScript analysis [javascript] (done) | time=611ms
INFO: Sensor JavaXmlSensor [java]
INFO: Sensor JavaXmlSensor [java] (done) | time=1ms
INFO: Sensor SonarTS [typescript]
INFO: Since SonarTS v2.0, TypeScript analysis is performed by SonarJS analyzer v6.0 or later. No TypeScript analysis is performed by SonarTS.
INFO: Sensor SonarTS [typescript] (done) | time=0ms
```

**To Reproduce**
1. Provision new quickstarter
2. First build of component shows the problem

**Expected behavior**
No exception. Compatible versions.

**Affected version**
 - OpenDevStack: master

**Other context**

Might affect the typescript-express quickstarter as well.

**Comment by michaelsauter** [comment]
Issue stems from https://github.com/opendevstack/ods-quickstarters/blob/master/e2e-cypress/files/package.json#L28.
