### ISSUE TITLE
Docgen not working with tests written with wiremock

### ISSUE THREAD

**Issue by carlosriess** [opendevstack/ods-quickstarters#468]
When running DocGen it stucks when it runs projects that use wiremock technology in theirs tests..

**To Reproduce**
1-Write a integration test using Spring Boot 2.2.7 that uses wiremock v2.26.3
2-The test should run fine and succesfully.
3-Integrate this project into a Release Manager with DocGen.
4-Run Developer Preview on Jira
5-A SocketTimeOutException exception ocurrs.
**Expected behavior**
All tests should pass and the documentation should be generated
**Troubleshooting**

From Openshift the pod agent is killed after DocGen sends the response..In DocGen log files there are no errors available.

**Screenshots**

**Affected version (please complete the following information):**
 - OpenShift: 3.11
 - OpenDevStack 1.0

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at unirest.shaded.org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at unirest.shaded.org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at unirest.shaded.org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
	at unirest.shaded.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at unirest.shaded.org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at unirest.shaded.org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at unirest.shaded.org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at unirest.shaded.org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at unirest.shaded.org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at unirest.shaded.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at unirest.shaded.org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at unirest.shaded.org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at unirest.shaded.org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at unirest.shaded.org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at unirest.shaded.org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at unirest.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at unirest.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at unirest.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:125)
	at kong.unirest.BaseRequest.asString(BaseRequest.java:180)
	at sun.reflect.GeneratedMethodAccessor10641.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.ods.service.DocGenService.createDocument(DocGenService.groovy:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
Caused: kong.unirest.UnirestException
	at kong.unirest.apache.ApacheClient.request(ApacheClient.java:133)
	at kong.unirest.BaseRequest.asString(BaseRequest.java:180)
	at sun.reflect.GeneratedMethodAccessor10641.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.ods.service.DocGenService.createDocument(DocGenService.groovy:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.ods.usecase.DocGenUseCase.createDocument(DocGenUseCase.groovy:32)
	at org.ods.usecase.LeVADocumentUseCase.createDTR(LeVADocumentUseCase.groovy:515)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:291)
	at org.ods.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:110)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:287)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:277)
	at phaseBuild.call(phaseBuild.groovy:41)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:530)
	at org.ods.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:110)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:450)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:84)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
Caused: java.lang.IllegalStateException: Error: Creating document of type 'DTR' for project 'xxxx' and repo 'xxxxx-aaaaaa' in phase 'Build' and stage 'POST_EXECUTE_REPO' has failed: java.net.SocketTimeoutException: Read timed out.
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:293)
	at org.ods.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:110)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:287)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2030)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2015)
	at com.cloudbees.groovy.cps.CpsDefaultGroovyMethods.each(CpsDefaultGroovyMethods:2056)
	at org.ods.scheduler.LeVADocumentScheduler.run(LeVADocumentScheduler.groovy:277)
	at phaseBuild.call(phaseBuild.groovy:41)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:530)
	at org.ods.util.PipelineUtil.executeBlockAndFailBuild(PipelineUtil.groovy:110)
	at org.ods.util.MROPipelineUtil.prepareExecutePhaseForRepoNamedJob(MROPipelineUtil.groovy:450)
	at ___cps.transform___(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.constructorCall(DefaultInvoker.java:25)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:97)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor426.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:186)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:370)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$200(CpsThreadGroup.java:93)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:282)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:270)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:66)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```
**Additional context**
If all tests using wiremock are excluded from build then DocGen passes succesfully and documentation is generated.

**Comment by metmajer** [comment]
@carlosriess thanks for creating the issue. Can you add some additional context?

1) Does the problem occur if you deactivate the generation of documents? You can do so by removing the `LevaDocs` capability in the Release Manager's `metadata.yml`.
2) Does the problem occur if you disable the WireMock test?
3) Are you using the SpringBoot Quickstarter and its JUnit testing framework to run your test? If you do, the Quickstarter will produce an xUnit file that you can introspect in our Jenkins master (you can open a terminal into your Jenkins master's container on OpenShift and inspect the filesystem under `/var/lib/jenkins/$pipelinename`. Can you verify that the file is there and that it contains the result for the test using Wiremock?
4) The read timeout indicates that the URL you want to connect to cannot be reached from within the pipeline. Now, this should lead to a failing test case, but should not affect the behavior of DocGen. At the point in time DocGen gets utilized, all your tests have already been exected. Can you verify that you can connect to the URL in the pipeline context?
5) Alan Bort has reported an exit code of 137 (out of memory) in one of the Jenkins slaves. He was assuming a scalability issue that occurs when running many tests. Can you share more information on this?

FYI @borja44 @clemensutschig

**Comment by clemensutschig** [comment]
Can you paste the whole jenkinslog... this is mega weird..

**Comment by metmajer** [comment]
WireMock uses a WireMock server that listens on a fixed or random port for connections to return test fixture data. WireMock uses `localhost` with a port in a safe port range. Curious why WireMock should be failing in this context.

@carlosriess a look at the test and setup of WireMock would also be interesting.

@clemensutschig according to a previous discussion, the Jenkins slave is killed immediately. When connecting to the Jenkins slave with a terminal, the container remains running because of the foreground `sh` process. Therein, Alan Bort had reported a 137 exit code. Strange!

**Comment by alanbort** [comment]
I believe the timeout to be a misleading error and caused by the unclean exit of the Jenkins Agent pod (seems to be killed by openshift). The timeout error appears in the jenkins log several minutes after the pod is killed, which would seem to indicate the timeout is in the master-agent communication and not any URL the pod itself is trying to reach.

The DocGen service shows no errors in the log, and immediately as the "DTR" line appears in its log we can see the Jenkins Agent pod is killed (from the OCP console, Jenkins takes several minutes to "notice")

**Comment by clemensutschig** [comment]
@alanbort  - the timeout is a call to the docgen service ...  https://github.com/opendevstack/ods-mro-jenkins-shared-library/blob/2.x/src/org/ods/service/DocGenService.groovy#L37 - so very likely you get a timeout from there ... ?! It's NOT a closed socket, so the thin is alive ... maybe a thread dump in the doc gen service can give more hints ...

you guysreally sure there is NO error in the doc gen service pod?

**Comment by alanbort** [comment]
![image](https://user-images.githubusercontent.com/5817381/94663699-43623d00-030a-11eb-995c-b3bcd966084c.png)
![image](https://user-images.githubusercontent.com/5817381/94663711-4826f100-030a-11eb-87c6-1ee0d703b98a.png)

**Comment by alanbort** [comment]
I've uploaded screenshots of the Jenkins Log and OpenShift console, Monitoring tab for <project>-cd. Note the two hour discrepancy between the two is expected (I think the hosts are UTC and OCP console is converting while Jenkins is not). These logs show the Jenkins Agent being killed immediately as the call to DocGen is issued on the agent.

Below is the log of DocGen, not sure if it's possible to enable timestamp with an Environment Variable or configmap.
![image](https://user-images.githubusercontent.com/5817381/94664094-ca171a00-030a-11eb-9800-bb985a2dae67.png)

**Comment by alanbort** [comment]
Note the timing between the call to DocGen and the error. The agent pod is killed long before the error is shown:
![image](https://user-images.githubusercontent.com/5817381/94664597-5cb7b900-030b-11eb-80be-5edb694e9c89.png)

**Comment by clemensutschig** [comment]
@alanbort - 3 requests:
a) please check the jenkins run / test results in the jenkins console - how many tests you see for this run... e.g in blue ocean (under tests) 
b) please turn on debug on the MRO and look specifically for the handover from the component build to the MRO (https://github.com/opendevstack/ods-quickstarters/blob/2.x/release-manager/Jenkinsfile.template#L5)
c) take a couple thread dumps INSIDE the doc gen pod during the execution (when the thing says "Creating document of type ..." in the jenkins log)   

docgen (and the mro call to it) has NOThing to do with the slave.. the call to docgen is executed from master .. (and not from the slave) ...

Above I see 20! minutes (8:29 -> 8:49) ... and we know from tracing that minimal timing is spent around this ... so hunch here - the amount of tests -> breaks (TAKES SUPER LONG) the template rendering in the doc gen service.

**Comment by metmajer** [comment]
@alanbort to add to Clemens' request above, we can create a dedicated branch for the ODS installation you are using and increase the socket connection settings (Clemens provided a link in his last sentence).

**Comment by alanbort** [comment]
We will work on the recommendations and provide feedback ASAP.

In the meantime we have strong indication the issue is not number of tests but rather the wiremock ones. This was confirmed by running with few tests including the wiremock ones which caused the error, and the same number of tests without wiremock which produced a valid DTR and successful pipeline completion. Furthermore, disabling only the Wiremock tests (keeping the other 1000+ unit tests) still completed the pipeline. 

We are working under the assumption that something the wiremock tests report that is different than other tests is, at least, related to the root cause of the issue. It seems the WireMock tests have content in the system-output tag in the xml with special characters including []. We are working on an isolated test case to determine if this string containg special characters could be related to the issue.

XML for regular test
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.XX.XXX.catalog.domain.ProductTest" tests="2" skipped="0" failures="0" errors="0" timestamp="2020-09-25T11:18:38" hostname="XXXXXXXXXXXX" time="0.166">
  <properties/>
  <testcase name="Product constructor that receives a product ID" classname="com.XX.XXX.catalog.domain.ProductTest" time="0.004"/>
  <testcase name="should set Product fields" classname="com.XX.XXX.catalog.domain.ProductTest" time="0.137"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

XML for test with WireMock
```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.XX.XXX.configuration_stack.adapter.client.forwarder.ForwarderClientTest" tests="5" skipped="0" failures="0" errors="0" timestamp="2020-09-25T11:18:52" hostname="WKS0000621516" time="24.857">
  <properties/>
  <testcase name="XXXP214 Build component does login and retry after receiving unauthorized" classname="com.XX.XXX.configuration_stack.adapter.client.forwarder.ForwarderClientTest" time="1.823"/>
  <testcase name="XXXP214 Get build status does login and retry after receiving unauthorized" classname="com.XX.XXX.configuration_stack.adapter.client.forwarder.ForwarderClientTest" time="2.252"/>
  <testcase name="XXXP210 When getBuildStatus returns a timeout, the client retries the call" classname="com.XX.XXX.configuration_stack.adapter.client.forwarder.ForwarderClientTest" time="10.927"/>
  <testcase name="XXXP210 When Build component returns a timeout, the client retries the call" classname="com.XX.XXX.configuration_stack.adapter.client.forwarder.ForwarderClientTest" time="9.265"/>
  <testcase name="XXXP229 XXXP240 XXXP287 should delete component" classname="com.XX.XXX.configuration_stack.adapter.client.forwarder.ForwarderClientTest" time="0.589"/>
  <system-out><![CDATA[13:18:52.354 [qtp781595164-96] DEBUG org.eclipse.jetty.util.thread.QueuedThreadPool - ran qtp781595164-96-acceptor-2@1c4b627c-NetworkTrafficServerConnector@71b0284a{​​​​​HTTP/1.1, (http/1.1)}​​​​​{​​​​​0.0.0.0:8080}​​​​​ in QueuedThreadPool[qtp781595164]@2e96321c{​​​​​STOPPED,8<=0<=14,i=5,r=-1,q=0}​​​​​[NO_TRY]
13:18:52.354 [qtp781595164-96] DEBUG org.eclipse.jetty.util.thread.QueuedThreadPool - Thread[qtp781595164-96,5,main] exited for QueuedThreadPool[qtp781595164]@2e96321c{​​​​​STOPPED,8<=0<=14,i=5,r=-1,q=0}​​​​​[NO_TRY]
13:18:52.355 [qtp781595164-94] DEBUG org.eclipse.jetty.util.thread.QueuedThreadPool - ran qtp781595164-94-acceptor-0@18c19611-NetworkTrafficServerConnector@71b0284a{​​​​​HTTP/1.1, (http/1.1)}​​​​​{​​​​​0.0.0.0:8080}​​​​​ in QueuedThreadPool[qtp781595164]@2e96321c{​​​​​STOPPED,8<=0<=14,i=5,r=-1,q=0}​​​​​[NO_TRY]
...
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
```

Note: this information was captured on a developer laptop and not in Jenkins as we have been unable to get the XMLs of a failed execution so far.

**Comment by clemensutschig** [comment]
then you are in docgen land :) (the threaddump should help us to understand this a little better, and build a testcase)

**Comment by carlosriess** [comment]
We think we found the solution....
The problem was in the <system-out> of the test result xml files...In test that use wiremock there is data here that cannot be correctly processed....We've told spring boot not to log anymore when testing...We add logback-text.xml in the root /src/test/resources with the content:

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <include resource="org/springframework/boot/logging/logback/base.xml"/>
  <root level="OFF" />
</configuration>

Seems DocGen has incompatibility with <system-out> content when is not blank.

**Comment by clemensutschig** [comment]
@carlosriess  - NICE .... file a bug against docgen - (with the content of the data that is sent over) ... - or even better, just fix it :)
