### ISSUE TITLE
ds-ml-service quickstarter test fails

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-quickstarters#531]
Latest AMI build fails with:
```
ESC[0;32m    amazon-ebs: + python3 jenkinsfile_helper.py --training-service http://localhost:8080 --username **** --password ****[0m
ESC[0;32m    amazon-ebs: Training server is on: http://localhost:8080ESC[0m
ESC[0;32m    amazon-ebs: Waiting for the training to be finished...ESC[0m
ESC[0;32m    amazon-ebs: Waiting for the training to be finished...ESC[0m
ESC[0;32m    amazon-ebs: Traceback (most recent call last):ESC[0m
ESC[0;32m    amazon-ebs:   File "jenkinsfile_helper.py", line 89, in <module>ESC[0m
ESC[0;32m    amazon-ebs:     training_finished = wait_for_training(host, auth)ESC[0m
ESC[0;32m    amazon-ebs:   File "jenkinsfile_helper.py", line 63, in wait_for_trainingESC[0m
ESC[0;32m    amazon-ebs:     raise Exception(res_json)ESC[0m
ESC[0;32m    amazon-ebs: Exception: {'finished': "Training ended with error: 'str' object has no attribute 'decode'"}ESC[0m
```

I can reproduce this on my machine.

@gerardcl @hugowschneider @sklingel Any ideas what might cause this?

**Comment by gerardcl** [comment]
The issue is also affecting ODS 3.x, I will provide a fix ASAP for 3.x first.
