### ISSUE TITLE
ODS AMI build failing due to error in test of qs e2e spock

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-quickstarters#544]
**Describe the bug**
This is affecting CI build of branches `master` and `3.x`.

It looks like the qs e2e spock depends on this library latest version `https://cdn.snigelweb.com/sncmp/latest/sncmp_stub.min.js`.
From the error message below something seems to be not compatible with library.

Error message:
```
[0;32m    amazon-ebs:     SEVERE: Error during JavaScript executionESC[0m
ESC[0;32m    amazon-ebs:     ======= EXCEPTION START ========ESC[0m
ESC[0;32m    amazon-ebs:     EcmaError: lineNumber=[1] column=[0] lineSource=[<no source>] name=[ReferenceError] sourceName=[https://cdn.snigelweb.com/sncmp/latest/sncmp_stub.min.js] message=[ReferenceError: "fu" is not defined. (https://cdn.snigelweb.com/sncmp/latest/sncmp_stub.min.js#1)]ESC[0m
ESC[0;32m    amazon-ebs:     com.gargoylesoftware.htmlunit.ScriptException: ReferenceError: "fu" is not defined. (https://cdn.snigelweb.com/sncmp/latest/sncmp_stub.min.js#1)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:883)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:617)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:534)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:336)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:763)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:739)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.execute(JavaScriptEngine.java:103)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.html.HtmlPage.loadExternalJavaScriptFile(HtmlPage.java:1002)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.html.HtmlScript.executeScriptIfNeeded(HtmlScript.java:362)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.html.HtmlScript$2.execute(HtmlScript.java:236)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.html.HtmlScript.onAllChildrenAddedToPage(HtmlScript.java:257)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:792)ESC[0m
ESC[0;32m    amazon-ebs:        at org.apache.xerces.parsers.AbstractSAXParser.endElement(Unknown Source)ESC[0m
ESC[0;32m    amazon-ebs:        at com.gargoylesoftware.htmlunit.html.HTMLParser$HtmlUnitDOMBuilder.endElement(HTMLParser.java:748)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.callEndElement(HTMLTagBalancer.java:1175)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.cyberneko.HTMLTagBalancer.endElement(HTMLTagBalancer.java:1115)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.cyberneko.filters.DefaultFilter.endElement(DefaultFilter.java:219)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.cyberneko.filters.NamespaceBinder.endElement(NamespaceBinder.java:303)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scanEndElement(HTMLScanner.java:3146)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.cyberneko.HTMLScanner$ContentScanner.scan(HTMLScanner.java:2074)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.cyberneko.HTMLScanner.scanDocument(HTMLScanner.java:922)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:438)ESC[0m
ESC[0;32m    amazon-ebs:        at net.sourceforge.htmlunit.cyberneko.HTMLConfiguration.parse(HTMLConfiguration.java:389)ESC[0m
ESC[0;32m    amazon-ebs:        at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)ESC[0m
``` 

How to reproduce:
- log into your odsbox
- pull latest ods-quickstarter branch and push it to bitbucket
- run the qs test for e2e spock

**Comment by stitakis** [comment]
@metmajer maybe you know the root of the problem... could you please have a quick look?

**Comment by metmajer** [comment]
According to @stitakis this intermediary issue was resolved by the library provider.
