### ISSUE TITLE
Docgen test failing in corporate proxy env - github not accessible

### ISSUE THREAD

**Issue by jssnull** [opendevstack/ods-quickstarters#632]
Command: 
```bash
make test-quickstarter QS=release-manager
```
Test suite failing:

```bash
app.GithubDocumentTemplatesStoreSpec.getTemplatesForVersion
```
Stacktrace
```bash
Mensaje de error
feign.RetryableException: http executing GET https://www.github.com/opendevstack/ods-document-generation-templates/archive/v1.0.zip
Traza
feign.RetryableException: http executing GET https://www.github.com/opendevstack/ods-document-generation-templates/archive/v1.0.zip
	at feign.FeignException.errorExecuting(FeignException.java:132)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:113)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78)
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
	at app.GithubDocumentTemplatesStore.getTemplatesForVersion(GithubDocumentTemplatesStore.groovy:40)
	at app.GithubDocumentTemplatesStoreSpec.getTemplatesForVersion(GithubDocumentTemplatesStoreSpec.groovy:100)
Caused by: java.net.UnknownHostException: http
	at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:797)
	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1368)
	at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1302)
	at okhttp3.Dns$1.lookup(Dns.java:39)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:170)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:136)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:81)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:171)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:167)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:108)
	... 4 more
Salida estandard
[2021-07-27 10:40:13,618]-[Test worker] INFO  app.App - [test@netty]: Server started in 215ms

  POST /document    [application/json]     [application/json]    (/anonymous)
  GET  /health                   [*/*]     [application/json]    (/anonymous)

listening on:
  http://localhost:9000/

[2021-07-27 10:40:13,629]-[Test worker] WARN  org.eclipse.jetty.server.NetworkTrafficServerConnector - Acceptors should be <= availableProcessors: NetworkTrafficServerConnector@5e329993{HTTP/1.1}{0.0.0.0:0}
[2021-07-27 10:40:13,631]-[Test worker] INFO  org.eclipse.jetty.server.Server - jetty-9.2.26.v20180806
[2021-07-27 10:40:13,636]-[Test worker] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@c9c7d91{/__admin,null,AVAILABLE}
[2021-07-27 10:40:13,637]-[Test worker] INFO  org.eclipse.jetty.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@54c6d6ac{/,null,AVAILABLE}
[2021-07-27 10:40:13,637]-[Test worker] INFO  org.eclipse.jetty.server.NetworkTrafficServerConnector - Started NetworkTrafficServerConnector@5e329993{HTTP/1.1}{0.0.0.0:9001}
[2021-07-27 10:40:13,637]-[Test worker] INFO  org.eclipse.jetty.server.Server - Started @68905ms
[2021-07-27 10:40:13,711]-[qtp115212580-269] INFO  / - RequestHandlerClass from context returned com.github.tomakehurst.wiremock.http.StubRequestHandler. Normalized mapped under returned 'null'
[2021-07-27 10:40:13,837]-[Test worker] INFO  org.eclipse.jetty.server.NetworkTrafficServerConnector - Stopped NetworkTrafficServerConnector@5e329993{HTTP/1.1}{0.0.0.0:9001}
[2021-07-27 10:40:13,900]-[Test worker] INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@54c6d6ac{/,null,UNAVAILABLE}
[2021-07-27 10:40:13,901]-[Test worker] INFO  org.eclipse.jetty.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@c9c7d91{/__admin,null,UNAVAILABLE}
[2021-07-27 10:40:13,901]-[Test worker] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - qtp115212580{STOPPING,8<=8<=10,i=7,q=7} Couldn't stop Thread[qtp115212580-271,5,]
[2021-07-27 10:40:13,901]-[Test worker] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - qtp115212580{STOPPING,8<=8<=10,i=4,q=6} Couldn't stop Thread[qtp115212580-275,5,]
[2021-07-27 10:40:13,901]-[Test worker] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - qtp115212580{STOPPING,8<=8<=10,i=4,q=6} Couldn't stop Thread[qtp115212580-266,5,main]
[2021-07-27 10:40:13,901]-[Test worker] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - qtp115212580{STOPPING,8<=8<=10,i=4,q=6} Couldn't stop Thread[qtp115212580-267,5,main]
[2021-07-27 10:40:13,901]-[Test worker] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - qtp115212580{STOPPING,8<=8<=10,i=4,q=6} Couldn't stop Thread[qtp115212580-270,5,main]
[2021-07-27 10:40:13,901]-[Test worker] WARN  org.eclipse.jetty.util.thread.QueuedThreadPool - qtp115212580{STOPPING,8<=8<=10,i=4,q=6} Couldn't stop Thread[qtp115212580-265,5,main]
[2021-07-27 10:40:15,451]-[Test worker] INFO  app.App - Stopped
```

Seems to be related with proxy settings

**Comment by clemensutschig** [comment]
@metmajer - well .. this is a tricky one .. the only thing I can envision is to create a gradle.properties in case `HTTP_PROXY` etc exists in the env ... thoughts?

**Comment by clemensutschig** [comment]
We could generate gradle.properties during provisioning

**Comment by clemensutschig** [comment]
@jssnull  - did you try as we discussed yesterday?

**Comment by jssnull** [comment]
yes, I got the same error
