### ISSUE TITLE
ODS AMI build fails due to failing jacoco report generation in springboot quickstarter

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-quickstarters#700]
This is a regression issue.

Jacoco report generation is failing in spring boot quickstarter since we upgraded the quickstarter to java 17. 

```
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: [Pipeline] { (Build and Unit Test)[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: [Pipeline] withEnv[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: [Pipeline] {[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: [Pipeline] sh[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: + /home/jenkins/use-j17.sh[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: Switching to java 17:[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: openjdk version "17.0.1" 2021-10-19[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: OpenJDK Runtime Environment 21.9 (build 17.0.1+12)[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: OpenJDK 64-Bit Server VM 21.9 (build 17.0.1+12, mixed mode, sharing)[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: javac 17.0.1[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: + ./gradlew clean build --stacktrace --no-daemon[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: Downloading https://services.gradle.org/distributions/gradle-7.3-bin.zip[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: ...........10%...........20%...........30%...........40%...........50%...........60%...........70%...........80%...........90%...........100%[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: Welcome to Gradle 7.3![0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: Here are the highlights of this release:[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs:  - Easily declare new test suites in Java projects[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs:  - Support for Java 17[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs:  - Support for Scala 3[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: For more details see https://docs.gradle.org/7.3/release-notes.html[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :clean UP-TO-DATE[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :compileJava[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :processResources[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :classes[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :bootJarMainClassName[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :bootJar[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :jar[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :assemble[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :compileTestJava[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :processTestResources NO-SOURCE[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :testClasses[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: > Task :test[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: 2022-01-11 15:52:22.933  INFO 491 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'[0m
[2022-01-11T15:52:58.420Z] [0;32m    amazon-ebs: 2022-01-11 15:52:22.934  INFO 491 --- [ionShutdownHook] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: 2022-01-11 15:52:22.937  INFO 491 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: 2022-01-11 15:52:22.940  INFO 491 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: > Task :jacocoTestReport FAILED[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: FAILURE: Build failed with an exception.[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: * What went wrong:[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: Execution failed for task ':jacocoTestReport'.[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: > Could not create service of type IsolatedAntBuilder using BuildScopeServices.createIsolatedAntBuilder().[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs:    > Could not inspect the Groovy system for ClassLoader VisitableURLClassLoader(ant-and-gradle-loader)[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: * Try:[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: > Run with --info or --debug option to get more log output.[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: > Run with --scan to get full insights.[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs:[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: * Exception is:[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jacocoTestReport'.[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)[0m
[2022-01-11T15:52:58.421Z] [0;32m    amazon-ebs: 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)[0m
```

**Comment by michaelsauter** [comment]
FYI @oalyman discovered this in ODS Pipeline: https://github.com/opendevstack/ods-pipeline/issues/386

**Comment by stitakis** [comment]
@michaelsauter thanks a lot for the link. I remember that I fixed this problem by removing `--no-daemon` but somehow I forgot to add it to the PR. I'll create fix PR with this change.

**Comment by oalyman** [comment]
@stitakis I would propose to leave the `--no-daemon` setting and rather set some JVM args like `org.gradle.jvmargs`.
This way it would start a single-use daemon that will be stopped after the build is finished.
You can tell this from the logs when you see the message:
`To honour the JVM settings for this build a single-use Daemon process will be forked`

**Comment by stitakis** [comment]
@oalyman I push a PR. It keeps the flag `--no-daemon` and defines in `gradle.properties` the JVM agrs `org.gradle.jvmars=...`. My manual test worked fine. Can you please review #701 ?
