### ISSUE TITLE
be-scala-play fails in odsBox generation tests

### ISSUE THREAD

**Issue by victorpablosceruelo** [opendevstack/ods-quickstarters#846]
**Describe the bug**
be-scala-play fails in odsBox generation tests

**To Reproduce**
Try to generate odsBox for master branch

**Expected behavior**
Should pass the tests

**Screenshots**
N/A

**Affected version (please complete the following information):**
 - OpenDevStack [master]

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
Attached
[be-scala-play-error.txt](https://github.com/opendevstack/ods-quickstarters/files/9573357/be-scala-play-error.txt)

**Additional context**
Can be related to the changes introduced, but not sure.
https://github.com/opendevstack/ods-core/pull/1181

**Comment by victorpablosceruelo** [comment]
Seems to be the folder 'target/test-reports' does not exist after executing tests, so the Jenkins master cannot unstash it.

```
java.io.IOException: Cannot use custom test directory 'target/test-reports' that does not exist![0m
[2022-09-15T01:54:56.425Z] [0;32m    amazon-ebs: run-unitt-be-scala-play-test-unitt-master-1: at org.ods.services.JenkinsService.stashTestResults(JenkinsService.groovy:25)[0m
[2022-09-15T01:54:56.425Z] [0;32m    amazon-ebs: run-unitt-be-scala-play-test-unitt-master-1: at org.ods.component.Pipeline.execute(Pipeline.groovy:281)[0m
[2022-09-15T01:54:56.425Z] [0;32m    amazon-ebs: run-unitt-be-scala-play-test-unitt-master-1: at ___cps.transform___(Native Method)[0m
```

Maybe @jafarre-bi or @jorge-romero can help us to see why this is happenning...
@braisvq1996 thanks for notifying.
